### ISSUE TITLE
expat directory empty, cannot build libstrophe

### ISSUE THREAD

**Issue by flamontagne** [metajack/libstrophe#2]
There was no copy of the xml parser in the expat sub folder. I have downloaded a copy of expat here http://sourceforge.net/projects/expat/ and extracted the content into the expat folder and was able to run 'make' without errors

**Comment by metajack** [comment]
You need to use git submodules to check it out.

git submodule init
git submodule update

Then expat will be there.

The documentation needs fixing to reflect these new instructions though.

**Comment by nlopes** [comment]
the submodule for expat is not working anymore. code.stanziq.com/expat.git seems to be unavailable.

**Comment by guysagy** [comment]
Hi, is there a solution for this issue stated above that "the submodule for expat is not working anymore. code.stanziq.com/expat.git seems to be unavailable" ?
Thank you for your help.

**Comment by tiagosa** [comment]
Yes,
you can get expat from its original project page.
http://sourceforge.net/projects/expat/
untar it inside the libstrophe root dir
then rename it to "expat"

**Comment by metajack** [comment]
This is now fixed.
