### ISSUE TITLE
Expat submodule repository not accessible 

### ISSUE THREAD

**Issue by DeepakDuggal** [metajack/libstrophe#22]
i have tried accessing the expat directory. Its not accesible and also libstrophe is giving compilation error.

**Comment by metajack** [comment]
I think perhaps you have an old version? Did you download it or use the latest checkout?

**Comment by DeepakDuggal** [comment]
i downloaded the repository as .zip file.

**Comment by DeepakDuggal** [comment]
i downloaded it from the expat sit and placed the files in the expat folder in the root directory.
