### ISSUE TITLE
"parser.c file is missing" error while building libstrophe solution

### ISSUE THREAD

**Issue by DeepakDuggal** [metajack/libstrophe#23]
while building libstrophe, its giving a compilation error that parser.c file is missing.

**Comment by metajack** [comment]
I'm guessing you are trying to build from Visual Studio? If so, you might need to update the VS project file as I haven't kept that up to date.

You can try renaming parser-expat.c to parser.c and see if that helps. The other platforms just include the file that is appropriate for the XML libriary dependency.

**Comment by DeepakDuggal** [comment]
thanks it is working now after renaming the parse-expat.c to parser.c.
