### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by dehlenbe** [metajack/libstrophe#3]
As with other 2 issues I saw listed here the build instructions are completely useless, at least for Ubuntu. I tried SCons with no success.

Here's how I built the static library.

1) You need to have automake and autoconf installed if you dont have them already.\
2) Change first line in bootstrap.h to read just aclocal  (no trailing -I /usr/local/... stuff)
3) Run ./bootstrap.h.
4) Run ./configure and make
5) Got errors about package "check". This is for unit testing in C. Use Synaptic Package Manager for easy installation.
6) Ran ./configure and make again.
4) I got errors about openssl.h not found. Go to Synaptic Package Manager and install development files for libcurl/openssl.
5) Ran ./configure and make again.
6) Got errors about expat.h not found. Use synaptic again to get development files for libexapt.
7) Ran ./configure and make again.
8) Still got errors about rules to make expat. Had to go to sourceforge and get actual source for expat. Extracted into expat sub-directory of where I was building libstrophe. Important to make sure files in the lib sub-directories are copied.
9) Ran ./configure and make again. Success! Havent tested static library (.a) file yet, but at least it built!

**Comment by dehlenbe** [comment]
Sorry. Made a type. Its bootstrap.sh not bootstrap.h.

**Comment by metajack** [comment]
This is now fixed.
